### ISSUE TITLE
How to transfer 'outputkeypoints_3d.npz' to csv file ?

### ISSUE THREAD

**Issue by RvMe** [Vegetebird/GraphMLP#1]
Thank your project, I want use this to analysis human pose angle,
So I need to transfer 'outputkeypoints_3d.npz' to csv file.

for example: I want from this
![图片](https://github.com/Vegetebird/GraphMLP/assets/56872189/d8d51ff4-c72f-430b-8e15-379e3e2f9a0b)
to this ↓↓↓
![图片](https://github.com/Vegetebird/GraphMLP/assets/56872189/f2081c38-5ce6-42c3-95a5-a08993c271f2)

However, when I np.load the npz, I was confuse by some many checkpoints and I cannot figure which point means which body section. I hope you can give me some tip to handle this data~
(loading figure ↓↓↓) 
![图片](https://github.com/Vegetebird/GraphMLP/assets/56872189/7bf26ab0-9319-415c-9ab1-9d7afce2c5d3)

Thx ! Best wish!

**Comment by RvMe** [comment]
OK, I figure it out~ anyone who meet same problem can saw the code below:  (put it in the same directory to main.py and run it)
[Start Work.zip](https://github.com/Vegetebird/GraphMLP/files/11575805/Start.Work.zip)

**Comment by jianlai123-123** [comment]
Hello, did you enter ground true to achieve the same effect as the paper? The effect I achieved was far from 34.6, with the best being 37.6. May I ask what is the reason for this? Looking forward to your reply, thank you. @RvMe

**Comment by RvMe** [comment]
@jianlai123-123 ,no, i use this algorithm to solve other problem

**Comment by jianlai123-123** [comment]
Okay, thank you for your reply.@RvMe

**Comment by jianlai123-123** [comment]
Hello, how can I visualize data? For example, the data shown in Figure 6 in the paper. Compare the visualization of ground true with the visualization of the model. Looking forward to your reply, thank you.@RvMe

**Comment by jianlai123-123** [comment]
你好，请问你知道怎么可视化3D姿态吗？@RvMe

**Comment by RvMe** [comment]
作者已经做出了了呀,你看看跑demo的那个代码生成的视频,已经它生成的附属的文件夹
&nbsp;


1059696078
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月7日(星期四) 晚上10:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Vegetebird/GraphMLP] How to transfer &#39;outputkeypoints_3d.npz&#39; to csv file ? (Issue #1)





 
***@***.***

**Comment by jianlai123-123** [comment]
好的，谢谢。
